-- =========================================================================
-- 1. LIMPIEZA DE BASE DE DATOS (Orden inverso para respetar Foreign Keys)
-- =========================================================================
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS albumes;
DROP TABLE IF EXISTS usuarios; -- Usuarios borrados antes que artistas si tienen FK
DROP TABLE IF EXISTS artistas;

-- =========================================================================
-- 2. CREACIÓN DE TABLAS (Adaptadas a tus Modelos Java)
-- =========================================================================

-- Tabla ARTISTAS (Equivalente a TITULARES)
CREATE TABLE artistas (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(255) NOT NULL,
                          nacionalidad VARCHAR(255) NOT NULL,
                          biografia TEXT, -- Usamos TEXT para biografías largas
                          is_deleted BOOLEAN DEFAULT FALSE,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Tabla USUARIOS (Con relación OneToOne opcional a Artista)
CREATE TABLE usuarios (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(255) NOT NULL,
                          apellidos VARCHAR(255) NOT NULL,
                          username VARCHAR(255) NOT NULL UNIQUE,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          is_deleted BOOLEAN DEFAULT FALSE,
                          artista_id BIGINT UNIQUE, -- Un usuario puede "gestionar" un artista
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CONSTRAINT FK_USUARIO_ARTISTA FOREIGN KEY (artista_id) REFERENCES artistas(id)
);

-- Tabla ROLES
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            roles ENUM('ADMIN', 'USER'),
                            CONSTRAINT FK_ROLES_USER FOREIGN KEY (user_id) REFERENCES usuarios(id)
);

-- Tabla ALBUMES (Equivalente a TARJETAS)
CREATE TABLE albumes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         titulo VARCHAR(255) NOT NULL,
                         genero VARCHAR(255) NOT NULL,
                         precio DOUBLE NOT NULL, -- O FLOAT(53)
                         fecha_lanzamiento DATE NOT NULL,
                         portada VARCHAR(255), -- URL de la imagen
                         descripcion TEXT, -- Descripción del álbum
                         uuid UUID DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
                         is_deleted BOOLEAN DEFAULT FALSE,
                         artista_id BIGINT NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT FK_ALBUM_ARTISTA FOREIGN KEY (artista_id) REFERENCES artistas(id)
);

-- =========================================================================
-- 3. INSERCIÓN DE DATOS (Artistas Top del Metalcore/Emo)
-- =========================================================================

-- ARTISTAS (ID 1, 2, 3, 4, 5)
INSERT INTO artistas (nombre, nacionalidad, biografia, created_at, updated_at) VALUES
                                                                                   ('Bring Me The Horizon', 'Reino Unido', 'Banda británica de rock que ha evolucionado desde el deathcore hasta el rock alternativo y pop rock.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('Bad Omens', 'Estados Unidos', 'Banda estadounidense de metalcore formada en 2015, conocida por su estilo cinemático y oscuro.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('My Chemical Romance', 'Estados Unidos', 'Iconos del rock emo y alternativo, famosos por The Black Parade.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('Motionless In White', 'Estados Unidos', 'Banda de metalcore con influencias góticas e industriales de Scranton, Pennsylvania.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('Sleep Token', 'Reino Unido', 'Misterioso colectivo británico anónimo que fusiona metal progresivo con indie pop y R&B.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ALBUMES (Asociados por ID de artista)

-- 1. Bring Me The Horizon (ID 1)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, portada, descripcion, artista_id, uuid, created_at, updated_at) VALUES
('Sempiternal', 'Metalcore', 19.99, '2013-04-01', '/images-cover-album/Sempiternal (Expanded Edition)_album_cover.jpg', 'Cuarto álbum de estudio que marcó un punto de inflexión en el sonido de BMTH, incorporando elementos electrónicos y orquestales al metalcore.', 1, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('That''s the Spirit', 'Rock Alternativo', 18.50, '2015-09-11', '/images-cover-album/That''s The Spirit_album_cover.jpg', 'Álbum que consolidó la transición de la banda hacia un sonido más accesible y experimental, alejándose del metalcore tradicional.', 1, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('POST HUMAN: NeX GEn', 'Hyperpop/Metal', 21.00, '2024-05-24', '/images-cover-album/POST HUMAN_ NeX GEn_album_cover.jpg', 'Segundo capítulo de la serie POST HUMAN, fusionando hyperpop, metal y elementos futuristas en una propuesta completamente innovadora.', 1, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 2. Bad Omens (ID 2)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, portada, descripcion, artista_id, uuid, created_at, updated_at) VALUES
('The Death of Peace of Mind', 'Metalcore Alternativo', 20.99, '2022-02-25', '/images-cover-album/THE DEATH OF PEACE OF MIND_track_cover.jpg', 'Tercer álbum conceptual que explora temas oscuros y existenciales con una producción cinemática y atmosférica única.', 2, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Finding God Before God Finds Me', 'Metalcore', 15.99, '2019-08-02', '/images-cover-album/Finding God Before God Finds Me (Deluxe)_album_cover.jpg', 'Segundo trabajo de estudio que estableció el sonido característico de Bad Omens, mezclando metalcore con elementos progresivos.', 2, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 3. My Chemical Romance (ID 3)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, portada, descripcion, artista_id, uuid, created_at, updated_at) VALUES
('The Black Parade', 'Emo/Rock Opera', 12.99, '2006-10-23', '/images-cover-album/The Black Parade_album_cover.jpg', 'Obra maestra conceptual que narra la muerte de "The Patient". Un álbum icónico del rock alternativo y emo de los 2000s.', 3, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Three Cheers for Sweet Revenge', 'Post-Hardcore', 11.50, '2004-06-08', '/images-cover-album/Three Cheers for Sweet Revenge_album_cover.jpg', 'Segundo álbum que catapultó a MCR a la fama internacional con su narrativa de venganza y amor post-mortem.', 3, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 4. Motionless In White (ID 4)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, portada, descripcion, artista_id, uuid, created_at, updated_at) VALUES
('Scoring the End of the World', 'Industrial Metal', 18.99, '2022-06-10', '/images-cover-album/Scoring The End Of The World_album_cover.jpg', 'Álbum que fusiona metalcore con influencias industriales y góticas, creando una atmósfera apocalíptica y cinematográfica.', 4, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Disguise', 'Nu Metalcore', 16.50, '2019-06-07', '/images-cover-album/Disguise_album_cover.jpg', 'Quinto trabajo de estudio que combina nu metal, metalcore y elementos industriales con letras introspectivas.', 4, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 5. Sleep Token (ID 5)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, portada, descripcion, artista_id, uuid, created_at, updated_at) VALUES
('Take Me Back To Eden', 'Alternative Metal', 24.99, '2023-05-19', '/images-cover-album/Take Me Back To Eden_album_cover.jpg', 'Tercer álbum de este misterioso colectivo que fusiona metal progresivo con R&B, pop y elementos atmosféricos de forma única.', 5, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sundowning', 'Progressive Metal', 14.99, '2019-11-21', '/images-cover-album/Sundowning (Deluxe)_album_cover.jpg', 'Debut de estudio que presentó al mundo la propuesta única de Sleep Token: metal progresivo con influencias de música alternativa y soul.', 5, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- =========================================================================
-- 4. USUARIOS (Admin y Managers de bandas)
-- =========================================================================

-- ADMIN (Sin artista asociado)
-- Contraseña: Admin1
INSERT INTO usuarios (nombre, apellidos, username, email, password, created_at, updated_at) VALUES
    ('Admin', 'Admin Admin', 'admin', 'admin@prueba.net',
     '$2a$10$vPaqZvZkz6jhb7U7k/V/v.5vprfNdOnh4sxi/qpPRkYTzPmFlI9p2', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (1, 'USER');
INSERT INTO user_roles (user_id, roles) VALUES (1, 'ADMIN');

-- USER 1: Oli Sykes (Manager de BMTH - ID 1)
-- Contraseña: User1
INSERT INTO usuarios (nombre, apellidos, username, email, password, artista_id, created_at, updated_at) VALUES
    ('Oliver', 'Sykes User', 'oli', 'oli@prueba.net',
     '$2a$12$RUq2ScW1Kiizu5K4gKoK4OTz80.DWaruhdyfi2lZCB.KeuXTBh0S.', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (2, 'USER');

-- USER 2: Noah Sebastian (Manager de Bad Omens - ID 2)
-- Contraseña: Test1
INSERT INTO usuarios (nombre, apellidos, username, email, password, artista_id, created_at, updated_at) VALUES
    ('Noah', 'Sebastian Test', 'noah', 'test@prueba.net',
     '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (3, 'USER');

-- USER 3: Gerard Way (Manager de MCR - ID 3)
-- Contraseña: Otro1
INSERT INTO usuarios (nombre, apellidos, username, email, password, artista_id, created_at, updated_at) VALUES
    ('Gerard', 'Way Otro', 'gerard', 'otro@prueba.net',
     '$2a$12$3Q4.UZbvBMBEvIwwjGEjae/zrIr6S50NusUlBcCNmBd2382eyU0bS', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (4, 'USER');
