-- =========================================================================
-- 1. LIMPIEZA DE BASE DE DATOS (Orden inverso para respetar Foreign Keys)
-- =========================================================================
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS albumes;
DROP TABLE IF EXISTS usuarios; -- Usuarios borrados antes que artistas si tienen FK
DROP TABLE IF EXISTS artistas;

-- =========================================================================
-- 2. CREACIÓN DE TABLAS (Adaptadas a tus Modelos Java)
-- =========================================================================

-- Tabla ARTISTAS (Equivalente a TITULARES)
CREATE TABLE artistas (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(255) NOT NULL,
                          nacionalidad VARCHAR(255) NOT NULL,
                          biografia TEXT, -- Usamos TEXT para biografías largas
                          is_deleted BOOLEAN DEFAULT FALSE,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Tabla USUARIOS (Con relación OneToOne opcional a Artista)
CREATE TABLE usuarios (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(255) NOT NULL,
                          apellidos VARCHAR(255) NOT NULL,
                          username VARCHAR(255) NOT NULL UNIQUE,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password VARCHAR(255) NOT NULL,
                          is_deleted BOOLEAN DEFAULT FALSE,
                          artista_id BIGINT UNIQUE, -- Un usuario puede "gestionar" un artista
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          CONSTRAINT FK_USUARIO_ARTISTA FOREIGN KEY (artista_id) REFERENCES artistas(id)
);

-- Tabla ROLES
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            roles ENUM('ADMIN', 'USER'),
                            CONSTRAINT FK_ROLES_USER FOREIGN KEY (user_id) REFERENCES usuarios(id)
);

-- Tabla ALBUMES (Equivalente a TARJETAS)
CREATE TABLE albumes (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         titulo VARCHAR(255) NOT NULL,
                         genero VARCHAR(255) NOT NULL,
                         precio DOUBLE NOT NULL, -- O FLOAT(53)
                         fecha_lanzamiento DATE NOT NULL,
                         portada VARCHAR(255), -- URL de la imagen
                         uuid UUID DEFAULT RANDOM_UUID() NOT NULL UNIQUE,
                         is_deleted BOOLEAN DEFAULT FALSE,
                         artista_id BIGINT NOT NULL,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         CONSTRAINT FK_ALBUM_ARTISTA FOREIGN KEY (artista_id) REFERENCES artistas(id)
);

-- =========================================================================
-- 3. INSERCIÓN DE DATOS (Artistas Top del Metalcore/Emo)
-- =========================================================================

-- ARTISTAS (ID 1, 2, 3, 4, 5)
INSERT INTO artistas (nombre, nacionalidad, biografia, created_at, updated_at) VALUES
                                                                                   ('Bring Me The Horizon', 'Reino Unido', 'Banda británica de rock que ha evolucionado desde el deathcore hasta el rock alternativo y pop rock.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('Bad Omens', 'Estados Unidos', 'Banda estadounidense de metalcore formada en 2015, conocida por su estilo cinemático y oscuro.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('My Chemical Romance', 'Estados Unidos', 'Iconos del rock emo y alternativo, famosos por The Black Parade.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('Motionless In White', 'Estados Unidos', 'Banda de metalcore con influencias góticas e industriales de Scranton, Pennsylvania.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                   ('Sleep Token', 'Reino Unido', 'Misterioso colectivo británico anónimo que fusiona metal progresivo con indie pop y R&B.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ALBUMES (Asociados por ID de artista)

-- 1. Bring Me The Horizon (ID 1)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, artista_id, uuid, created_at, updated_at) VALUES
                                                                                                              ('Sempiternal', 'Metalcore', 19.99, '2013-04-01', 1, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                              ('That''s the Spirit', 'Rock Alternativo', 18.50, '2015-09-11', 1, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                              ('POST HUMAN: NeX GEn', 'Hyperpop/Metal', 21.00, '2024-05-24', 1, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 2. Bad Omens (ID 2)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, artista_id, uuid, created_at, updated_at) VALUES
                                                                                                              ('The Death of Peace of Mind', 'Metalcore Alternativo', 20.99, '2022-02-25', 2, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                              ('Finding God Before God Finds Me', 'Metalcore', 15.99, '2019-08-02', 2, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 3. My Chemical Romance (ID 3)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, artista_id, uuid, created_at, updated_at) VALUES
                                                                                                              ('The Black Parade', 'Emo/Rock Opera', 12.99, '2006-10-23', 3, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                              ('Three Cheers for Sweet Revenge', 'Post-Hardcore', 11.50, '2004-06-08', 3, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 4. Motionless In White (ID 4)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, artista_id, uuid, created_at, updated_at) VALUES
                                                                                                              ('Scoring the End of the World', 'Industrial Metal', 18.99, '2022-06-10', 4, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                              ('Disguise', 'Nu Metalcore', 16.50, '2019-06-07', 4, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 5. Sleep Token (ID 5)
INSERT INTO albumes (titulo, genero, precio, fecha_lanzamiento, artista_id, uuid, created_at, updated_at) VALUES
                                                                                                              ('Take Me Back To Eden', 'Alternative Metal', 24.99, '2023-05-19', 5, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                                              ('Sundowning', 'Progressive Metal', 14.99, '2019-11-21', 5, RANDOM_UUID(), CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);


-- =========================================================================
-- 4. USUARIOS (Admin y Managers de bandas)
-- =========================================================================

-- ADMIN (Sin artista asociado)
-- Pass: Admin1
INSERT INTO usuarios (nombre, apellidos, username, email, password, created_at, updated_at) VALUES
    ('Admin', 'Supremo', 'admin', 'admin@albumes.com', 'admin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (1, 'ADMIN');
INSERT INTO user_roles (user_id, roles) VALUES (1, 'USER');

-- USER 1: Oli Sykes (Manager de BMTH - ID 1)
-- Pass: User1
INSERT INTO usuarios (nombre, apellidos, username, email, password, artista_id, created_at, updated_at) VALUES
    ('Oliver', 'Sykes', 'oli', 'oli@bmth.com', 'Oliver', 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (2, 'USER');

-- USER 2: Noah Sebastian (Manager de Bad Omens - ID 2)
-- Pass: User1 (reutilizada para facilitar pruebas)
INSERT INTO usuarios (nombre, apellidos, username, email, password, artista_id, created_at, updated_at) VALUES
    ('Noah', 'Sebastian', 'noah', 'noah@badomens.com', 'Noah', 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (3, 'USER');

-- USER 3: Gerard Way (Manager de MCR - ID 3)
-- Pass: User1
INSERT INTO usuarios (nombre, apellidos, username, email, password, artista_id, created_at, updated_at) VALUES
    ('Gerard', 'Way', 'gerard', 'gerard@mcr.com', 'Gerard', 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO user_roles (user_id, roles) VALUES (4, 'USER');