/*
-- Borra la tabla si existe
drop table if exists ALBUMES;
drop table if exists ARTISTAS;
drop table if exists USER_ROLES;
drop table if exists USUARIOS;

-- Crea la tabla ARTISTAS (Equivalente a TITULARES)
create table ARTISTAS (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(255) not null,
    nacionalidad varchar(255) not null,
    fecha_nacimiento date,
    imagen varchar(255),
    biografia TEXT,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);

-- Crea la tabla ALBUMES (Equivalente a TARJETAS)
create table ALBUMES (
    id bigint generated by default as identity PRIMARY KEY,
    titulo varchar(255) not null,
    genero varchar(255) not null,
    fecha_lanzamiento date not null,
    precio float(53) not null,
    portada varchar(255),
    descripcion TEXT,
    artista_id bigint not null,
    is_deleted boolean default false,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    uuid uuid not null unique
);

create table user_roles (
    user_id bigint not null,
    roles enum ('ADMIN','USER')
);

create table USUARIOS (
    id bigint generated by default as identity PRIMARY KEY,
    nombre varchar(255) not null,
    apellidos varchar(255) not null,
    username varchar(255) not null unique,
    email varchar(255) not null unique,
    password varchar(255) not null,
    is_deleted boolean default false,
    artista_id bigint unique,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP not null
);
*/

-- Filas de ejemplo ARTISTAS
INSERT INTO ARTISTAS (nombre, nacionalidad, fecha_nacimiento, biografia)
VALUES ('The Beatles', 'Reino Unido', '1960-01-01', 'Legendaria banda de rock.');
INSERT INTO ARTISTAS (nombre, nacionalidad, fecha_nacimiento, biografia)
VALUES ('Queen', 'Reino Unido', '1970-01-01', 'Banda de rock británica.');
INSERT INTO ARTISTAS (nombre, nacionalidad, fecha_nacimiento, biografia)
VALUES ('Rosalía', 'España', '1992-09-25', 'Cantante y compositora española.');

-- Filas de ejemplo ALBUMES (Usamos los IDs de los artistas creados arriba: 1, 2, 3)
INSERT INTO ALBUMES (titulo, genero, fecha_lanzamiento, precio, artista_id, uuid)
VALUES ('Abbey Road', 'Rock', '1969-09-26', 29.99, 1, UUID());
INSERT INTO ALBUMES (titulo, genero, fecha_lanzamiento, precio, artista_id, uuid)
VALUES ('A Night at the Opera', 'Rock', '1975-11-21', 19.99, 2, UUID());
INSERT INTO ALBUMES (titulo, genero, fecha_lanzamiento, precio, artista_id, uuid)
VALUES ('Motomami', 'Pop Experimental', '2022-03-18', 24.99, 3, UUID());

-- Datos de ejemplo USUARIOS
-- Contraseña: Admin1
-- No está asociado a ningún artista (equivalente a titular)
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Admin', 'Admin Admin', 'admin', 'admin@prueba.net',
        '$2a$10$vPaqZvZkz6jhb7U7k/V/v.5vprfNdOnh4sxi/qpPRkYTzPmFlI9p2');

insert into USER_ROLES (user_id, roles)
values (1, 'USER');
insert into USER_ROLES (user_id, roles)
values (1, 'ADMIN');

-- Contraseña: User1
-- Asociado al artista 2 (Queen)
insert into USUARIOS (nombre, apellidos, username, email, password, artista_id)
values ('Jose', 'Jose User', 'jose', 'user@prueba.net',
        '$2a$12$RUq2ScW1Kiizu5K4gKoK4OTz80.DWaruhdyfi2lZCB.KeuXTBh0S.', 2);
insert into USER_ROLES (user_id, roles)
values (2, 'USER');

-- Contraseña: Test1
-- Sin artista asociado
insert into USUARIOS (nombre, apellidos, username, email, password)
values ('Test', 'Test Test', 'test', 'test@prueba.net',
        '$2a$10$Pd1yyq2NowcsDf4Cpf/ZXObYFkcycswqHAqBndE1wWJvYwRxlb.Pu');
insert into USER_ROLES (user_id, roles)
values (2, 'USER');

-- Contraseña: Otro1
-- Asociado al artista 3 (Rosalía)
insert into USUARIOS (nombre, apellidos, username, email, password, artista_id)
values ('María', 'María Otro', 'maría', 'otro@prueba.net',
        '$2a$12$3Q4.UZbvBMBEvIwwjGEjae/zrIr6S50NusUlBcCNmBd2382eyU0bS', 3);
insert into USER_ROLES (user_id, roles)
values (3, 'USER');