# Albumes
auth.password=Contrasena
auth.username=Usuario
auth.email=Email
auth.logout=Cerrar Sesion
auth.register=Registrarse
auth.login=Iniciar Sesion
# Autenticacion

nav.new.albumes=Nuevo album
nav.logout=Cerrar Sesion
nav.login=Conexion
nav.home=Inicio
# Barra de navegacion

albumes.borrar.titulo=Borrar album
albumes.borrar.mensaje=Confirma el borrado del album "{0}"?
albumes.search=Buscar
label.album.detalle=Detalle del album
label.album.genero=Genero
label.album.titulo=Titulo
label.album.empty=No se han encontrado albumes

