### getAll (debería devolver todos los albumes al venir la petición de un origen autorizado)
GET http://localhost:3000/api/v1/albumes
Origin: http://mifrontend.es

### getAll (debería devolver un 403 al no venit la petición de un origen autorizado)
GET http://localhost:3000/api/v1/albumes
Origin: http://otrodominio.es