-- Borra las tablas si existen (orden inverso por las claves foráneas)
DROP TABLE IF EXISTS ALBUMES;
DROP TABLE IF EXISTS ARTISTAS;

-- Crea la tabla ARTISTAS
CREATE TABLE ARTISTAS (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          nombre VARCHAR(255) NOT NULL UNIQUE,
                          is_deleted BOOLEAN DEFAULT FALSE,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Crea la tabla ALBUMES
CREATE TABLE ALBUMES (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         nombre VARCHAR(255) NOT NULL,
                         genero VARCHAR(255) NOT NULL,
                         precio FLOAT(24) NOT NULL,
                         artista_id BIGINT,
                         is_deleted BOOLEAN DEFAULT FALSE,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                         uuid UUID NOT NULL UNIQUE
);

ALTER TABLE IF EXISTS ALBUMES
    ADD CONSTRAINT fk_albumes_artistas_artista_id FOREIGN KEY (artista_id) REFERENCES ARTISTAS(id);